name: Linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: js/ts linting
        run: npm run lint
      - name: css linting
        run: npm run stylelint
      - name: unit testing
        run: npm run test
      - name: chromatic screenshot testing
        run: npm run chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: production build
        run: npm run build:prod
      - name: storybook build
        run: npm run build-storybook
